[package]
name = "codegen-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
allocator-api2 = "0.2"
protocrap = { path = "..", features = ["codegen"] }
serde = { version = "1.0.228" }
serde_json = "1.0.104"

[dev-dependencies]
criterion = "0.5"
rand = "0.8"
